### ISSUE TITLE
Characters not getting keys on joining

### ISSUE THREAD

**Issue by KoolAiddTV** [Xseba360/esx_locksystem#13]
I'm using eden garage and kashacters, when people join the server they don't get the keys to the vehicles they own

**Comment by iSentrie** [comment]
Cus u have to add hasKeys function in to ur code

**Comment by KoolAiddTV** [comment]
how do I fix the error "Can't create the vehicle instance. Missing argument PLATE"
It's happening on eden garage and esx policejob

**Comment by iSentrie** [comment]
do you even imported sql table?

**Comment by KoolAiddTV** [comment]
Yes I imported the sql

**Comment by EGUltraTM** [comment]
> 
> 
> Cus u have to add hasKeys function in to ur code

How can we add the haskey function?
